ERROR_GLOBAL = 'Токен практикума PRACTICUM_TOKEN, не задан в файле .env'
ERROR_GLOBAL1 = 'Токен телеграм бота TELEGRAM_TOKEN, не задан в файле .env'
ERROR_GLOBAL2 = 'TELEGRAM_CHAT_ID не задан в файле .env'
ERROR_GLOBAL3 = 'Не все переменные окружения заданы.'
ERROR_GLOBAL_OK = 'Все переменные окружения присутствуют в файле .env'
BOT_OK = 'Сообщение отправлено'
BOR_ERROR = 'ошибка телграм бота\n{}'
API_ERROR1 = 'Ошибка при запросе к API \nurl={}, headers={}, params={}.\n{}'
API_ERROR = 'код ответа Api {}'
JSON_ERROR = 'не соответствуют JSON-формату \n{}'
NO_DICT = 'ответ сервера, не является словарем {}'
NO_LIST = 'ответ сервера, homeworks не является списком {}'
NO_INFO = 'в ответе сервера нет информации.'
API_ERROR2 = 'в ответе сервера нет значения homework_name.'
STATUS_MESSAGE = 'Изменился статус проверки работы "{}". {}'
NOT_STATUS = 'Статус не определен'
STATUS_CHANGED = 'Статус изменился.'
ERROR_MESSAGE = 'Сбой в работе программы: {}'
